steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/elet-meteorologia-graphcast-dev/graphcast:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/elet-meteorologia-graphcast-dev/graphcast:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'tpus'
  - 'create'
  - 'elet-graphcast-tpu-vm3'
  - '--zone=us-central1-a'
  - '--accelerator-type=v3-8'
  - '--version=tpu-vm-tf-2.11.0'
#  - '--preemptible'  # Optional: Use a preemptible TPU
#  - '--metadata-from-file=startup-script=startup.sh'
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/elet-meteorologia-graphcast-dev/graphcast:latest'