steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/bryan-dev-396914/graphcast-repo/graphcast-image', '.']
images:
- 'us-central1-docker.pkg.dev/bryan-dev-396914/graphcast-repo/graphcast-image'